"""SUPLA protocol constants from supla-common/proto.h."""

from __future__ import annotations

SUPLA_TAG = b"SUPLA"
SUPLA_TAG_SIZE = 5

SUPLA_PROTO_VERSION = 28
SUPLA_PROTO_VERSION_MIN = 1

SUPLA_SOFTVER_MAXSIZE = 21
SUPLA_GUID_SIZE = 16
SUPLA_AUTHKEY_SIZE = 16
SUPLA_LOCATION_PWD_MAXSIZE = 33
SUPLA_DEVICE_NAME_MAXSIZE = 201
SUPLA_EMAIL_MAXSIZE = 256
SUPLA_SERVER_NAME_MAXSIZE = 65
SUPLA_CHANNELVALUE_SIZE = 8
SUPLA_CHANNELMAXCOUNT = 128
SUPLA_TIMEZONE_MAXSIZE = 51
SUPLA_CAPTION_MAXSIZE = 402

# Packet header after tag: version(1) + rr_id(4) + call_id(4) + data_size(4)
SUPLA_PACKET_HEADER_SIZE = 13
SUPLA_PACKET_MIN_SIZE = SUPLA_TAG_SIZE + SUPLA_PACKET_HEADER_SIZE + SUPLA_TAG_SIZE

SOFT_VERSION = "supla-hacs/0.1.0"
DEFAULT_ACTIVITY_TIMEOUT = 100
DEFAULT_TCP_HOST = "0.0.0.0"
DEFAULT_TCP_PORT = 2015
DEFAULT_TLS_PORT = 2016
DEFAULT_HTTP_HOST = "0.0.0.0"
DEFAULT_HTTP_PORT = 8088
HTTP_SENDER_ID = 1

# device/client <-> server
SUPLA_DCS_CALL_GETVERSION = 10
SUPLA_SDC_CALL_GETVERSION_RESULT = 20
SUPLA_SDC_CALL_VERSIONERROR = 30
SUPLA_DCS_CALL_PING_SERVER = 40
SUPLA_SDC_CALL_PING_SERVER_RESULT = 50
SUPLA_DS_CALL_REGISTER_DEVICE = 60
SUPLA_DS_CALL_REGISTER_DEVICE_B = 65
SUPLA_DS_CALL_REGISTER_DEVICE_C = 67
SUPLA_DS_CALL_REGISTER_DEVICE_D = 68
SUPLA_DS_CALL_REGISTER_DEVICE_E = 69
SUPLA_SD_CALL_REGISTER_DEVICE_RESULT = 70
SUPLA_SD_CALL_REGISTER_DEVICE_RESULT_B = 71
SUPLA_DS_CALL_REGISTER_DEVICE_F = 75
SUPLA_DS_CALL_REGISTER_DEVICE_G = 76
SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED = 100
SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED_B = 102
SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED_C = 103
SUPLA_DS_CALL_DEVICE_CHANNEL_EXTENDEDVALUE_CHANGED = 105
SUPLA_SD_CALL_CHANNEL_SET_VALUE = 110
SUPLA_DS_CALL_CHANNEL_SET_VALUE_RESULT = 120
SUPLA_DCS_CALL_SET_ACTIVITY_TIMEOUT = 210
SUPLA_SDC_CALL_SET_ACTIVITY_TIMEOUT_RESULT = 220
SUPLA_DS_CALL_GET_FIRMWARE_UPDATE_URL = 300
SUPLA_SD_CALL_GET_FIRMWARE_UPDATE_URL_RESULT = 310
SUPLA_DCS_CALL_GET_REGISTRATION_ENABLED = 320
SUPLA_SDC_CALL_GET_REGISTRATION_ENABLED_RESULT = 330
SUPLA_DCS_CALL_GET_USER_LOCALTIME = 480
SUPLA_DCS_CALL_GET_USER_LOCALTIME_RESULT = 490
SUPLA_CSD_CALL_GET_CHANNEL_STATE = 500
SUPLA_DSC_CALL_CHANNEL_STATE_RESULT = 510
SUPLA_DS_CALL_GET_CHANNEL_FUNCTIONS = 620
SUPLA_SD_CALL_GET_CHANNEL_FUNCTIONS_RESULT = 630
SUPLA_DCS_CALL_SET_CHANNEL_CAPTION = 640
SUPLA_SCD_CALL_SET_CHANNEL_CAPTION_RESULT = 650
SUPLA_DS_CALL_GET_CHANNEL_CONFIG = 680
SUPLA_SD_CALL_GET_CHANNEL_CONFIG_RESULT = 690
SUPLA_DS_CALL_SET_CHANNEL_CONFIG = 681
SUPLA_SD_CALL_SET_CHANNEL_CONFIG_RESULT = 691
SUPLA_SD_CALL_SET_CHANNEL_CONFIG = 682
SUPLA_DS_CALL_SET_CHANNEL_CONFIG_RESULT = 692
SUPLA_SD_CALL_CHANNEL_CONFIG_FINISHED = 683
SUPLA_DS_CALL_SET_DEVICE_CONFIG = 684
SUPLA_SD_CALL_SET_DEVICE_CONFIG_RESULT = 694
SUPLA_SD_CALL_SET_DEVICE_CONFIG = 685
SUPLA_DS_CALL_SET_DEVICE_CONFIG_RESULT = 695
SUPLA_DS_CALL_ACTIONTRIGGER = 700
SUPLA_DS_CALL_REGISTER_PUSH_NOTIFICATION = 1100
SUPLA_DS_CALL_SEND_PUSH_NOTIFICATION = 1110
SUPLA_DS_CALL_SET_SUBDEVICE_DETAILS = 1260

SUPLA_RESULTCODE_TRUE = 3

SUPLA_CONFIG_RESULT_FALSE = 0
SUPLA_CONFIG_RESULT_TRUE = 1
SUPLA_CONFIG_RESULT_DATA_ERROR = 2
SUPLA_CONFIG_RESULT_TYPE_NOT_SUPPORTED = 3
SUPLA_CONFIG_RESULT_FUNCTION_NOT_SUPPORTED = 4
SUPLA_CONFIG_RESULT_LOCAL_CONFIG_DISABLED = 5
SUPLA_CONFIG_RESULT_NOT_ALLOWED = 6
SUPLA_CONFIG_RESULT_DEVICE_NOT_FOUND = 7

CONFIG_RESULT_NAMES: dict[int, str] = {
    SUPLA_CONFIG_RESULT_FALSE: "rejected",
    SUPLA_CONFIG_RESULT_TRUE: "accepted",
    SUPLA_CONFIG_RESULT_DATA_ERROR: "malformed configuration",
    SUPLA_CONFIG_RESULT_TYPE_NOT_SUPPORTED: "configuration type not supported",
    SUPLA_CONFIG_RESULT_FUNCTION_NOT_SUPPORTED: "channel function not supported",
    SUPLA_CONFIG_RESULT_LOCAL_CONFIG_DISABLED: "local configuration disabled",
    SUPLA_CONFIG_RESULT_NOT_ALLOWED: "not allowed",
    SUPLA_CONFIG_RESULT_DEVICE_NOT_FOUND: "device not found",
}

SUPLA_CONFIG_TYPE_DEFAULT = 0
SUPLA_CONFIG_TYPE_WEEKLY_SCHEDULE = 2
SUPLA_CONFIG_TYPE_ALT_WEEKLY_SCHEDULE = 3
SUPLA_CONFIG_TYPE_OCR = 4
SUPLA_CONFIG_TYPE_EXTENDED = 5

# Device capability flags.
SUPLA_DEVICE_FLAG_SLEEP_MODE_ENABLED = 0x0020
SUPLA_DEVICE_FLAG_DEVICE_CONFIG_SUPPORTED = 0x0080
SUPLA_CHANNEL_FLAG_RUNTIME_CHANNEL_CONFIG_UPDATE = 0x08000000

# Channel types
SUPLA_CHANNELTYPE_BINARYSENSOR = 1000
SUPLA_CHANNELTYPE_SENSORNC = 1010
SUPLA_CHANNELTYPE_DISTANCESENSOR = 1020
SUPLA_CHANNELTYPE_CALLBUTTON = 1500
SUPLA_CHANNELTYPE_RELAYHFD4 = 2000
SUPLA_CHANNELTYPE_RELAYG5LA1A = 2010
SUPLA_CHANNELTYPE_2XRELAYG5LA1A = 2020
SUPLA_CHANNELTYPE_RELAY = 2900
SUPLA_CHANNELTYPE_THERMOMETERDS18B20 = 3000
SUPLA_CHANNELTYPE_DHT11 = 3010
SUPLA_CHANNELTYPE_DHT22 = 3020
SUPLA_CHANNELTYPE_DHT21 = 3022
SUPLA_CHANNELTYPE_AM2302 = 3030
SUPLA_CHANNELTYPE_AM2301 = 3032
SUPLA_CHANNELTYPE_THERMOMETER = 3034
SUPLA_CHANNELTYPE_HUMIDITYSENSOR = 3036
SUPLA_CHANNELTYPE_HUMIDITYANDTEMPSENSOR = 3038
SUPLA_CHANNELTYPE_WINDSENSOR = 3042
SUPLA_CHANNELTYPE_PRESSURESENSOR = 3044
SUPLA_CHANNELTYPE_RAINSENSOR = 3048
SUPLA_CHANNELTYPE_WEIGHTSENSOR = 3050
SUPLA_CHANNELTYPE_WEATHER_STATION = 3100
SUPLA_CHANNELTYPE_CONTAINER = 3200
SUPLA_CHANNELTYPE_DIMMER = 4000
SUPLA_CHANNELTYPE_RGBLEDCONTROLLER = 4010
SUPLA_CHANNELTYPE_DIMMERANDRGBLED = 4020
SUPLA_CHANNELTYPE_ELECTRICITY_METER = 5000
SUPLA_CHANNELTYPE_IMPULSE_COUNTER = 5010
SUPLA_CHANNELTYPE_THERMOSTAT = 6000
SUPLA_CHANNELTYPE_THERMOSTAT_HEATPOL_HOMEPLUS = 6010
SUPLA_CHANNELTYPE_HVAC = 6100
SUPLA_CHANNELTYPE_VALVE_OPENCLOSE = 7000
SUPLA_CHANNELTYPE_VALVE_PERCENTAGE = 7010
SUPLA_CHANNELTYPE_BRIDGE = 8000
SUPLA_CHANNELTYPE_GENERAL_PURPOSE_MEASUREMENT = 9000
SUPLA_CHANNELTYPE_GENERAL_PURPOSE_METER = 9010
SUPLA_CHANNELTYPE_ENGINE = 10000
SUPLA_CHANNELTYPE_ACTIONTRIGGER = 11000
SUPLA_CHANNELTYPE_DIGIGLASS = 12000

CHANNEL_TYPE_NAMES: dict[int, str] = {
    SUPLA_CHANNELTYPE_BINARYSENSOR: "BINARYSENSOR",
    SUPLA_CHANNELTYPE_SENSORNC: "SENSORNC",
    SUPLA_CHANNELTYPE_DISTANCESENSOR: "DISTANCESENSOR",
    SUPLA_CHANNELTYPE_CALLBUTTON: "CALLBUTTON",
    SUPLA_CHANNELTYPE_RELAYHFD4: "RELAYHFD4",
    SUPLA_CHANNELTYPE_RELAYG5LA1A: "RELAYG5LA1A",
    SUPLA_CHANNELTYPE_2XRELAYG5LA1A: "2XRELAYG5LA1A",
    SUPLA_CHANNELTYPE_RELAY: "RELAY",
    SUPLA_CHANNELTYPE_THERMOMETERDS18B20: "THERMOMETERDS18B20",
    SUPLA_CHANNELTYPE_DHT11: "DHT11",
    SUPLA_CHANNELTYPE_DHT22: "DHT22",
    SUPLA_CHANNELTYPE_DHT21: "DHT21",
    SUPLA_CHANNELTYPE_AM2302: "AM2302",
    SUPLA_CHANNELTYPE_AM2301: "AM2301",
    SUPLA_CHANNELTYPE_THERMOMETER: "THERMOMETER",
    SUPLA_CHANNELTYPE_HUMIDITYSENSOR: "HUMIDITYSENSOR",
    SUPLA_CHANNELTYPE_HUMIDITYANDTEMPSENSOR: "HUMIDITYANDTEMPSENSOR",
    SUPLA_CHANNELTYPE_WINDSENSOR: "WINDSENSOR",
    SUPLA_CHANNELTYPE_PRESSURESENSOR: "PRESSURESENSOR",
    SUPLA_CHANNELTYPE_RAINSENSOR: "RAINSENSOR",
    SUPLA_CHANNELTYPE_WEIGHTSENSOR: "WEIGHTSENSOR",
    SUPLA_CHANNELTYPE_WEATHER_STATION: "WEATHER_STATION",
    SUPLA_CHANNELTYPE_CONTAINER: "CONTAINER",
    SUPLA_CHANNELTYPE_DIMMER: "DIMMER",
    SUPLA_CHANNELTYPE_RGBLEDCONTROLLER: "RGBLEDCONTROLLER",
    SUPLA_CHANNELTYPE_DIMMERANDRGBLED: "DIMMERANDRGBLED",
    SUPLA_CHANNELTYPE_ELECTRICITY_METER: "ELECTRICITY_METER",
    SUPLA_CHANNELTYPE_IMPULSE_COUNTER: "IMPULSE_COUNTER",
    SUPLA_CHANNELTYPE_THERMOSTAT: "THERMOSTAT",
    SUPLA_CHANNELTYPE_THERMOSTAT_HEATPOL_HOMEPLUS: "THERMOSTAT_HEATPOL_HOMEPLUS",
    SUPLA_CHANNELTYPE_HVAC: "HVAC",
    SUPLA_CHANNELTYPE_VALVE_OPENCLOSE: "VALVE_OPENCLOSE",
    SUPLA_CHANNELTYPE_VALVE_PERCENTAGE: "VALVE_PERCENTAGE",
    SUPLA_CHANNELTYPE_BRIDGE: "BRIDGE",
    SUPLA_CHANNELTYPE_GENERAL_PURPOSE_MEASUREMENT: "GENERAL_PURPOSE_MEASUREMENT",
    SUPLA_CHANNELTYPE_GENERAL_PURPOSE_METER: "GENERAL_PURPOSE_METER",
    SUPLA_CHANNELTYPE_ENGINE: "ENGINE",
    SUPLA_CHANNELTYPE_ACTIONTRIGGER: "ACTIONTRIGGER",
    SUPLA_CHANNELTYPE_DIGIGLASS: "DIGIGLASS",
}

# Channel functions
SUPLA_CHANNELFNC_NONE = 0
SUPLA_CHANNELFNC_CONTROLLINGTHEGATEWAYLOCK = 10
SUPLA_CHANNELFNC_CONTROLLINGTHEGATE = 20
SUPLA_CHANNELFNC_CONTROLLINGTHEGARAGEDOOR = 30
SUPLA_CHANNELFNC_THERMOMETER = 40
SUPLA_CHANNELFNC_HUMIDITY = 42
SUPLA_CHANNELFNC_HUMIDITYANDTEMPERATURE = 45
SUPLA_CHANNELFNC_OPENINGSENSOR_GATEWAY = 50
SUPLA_CHANNELFNC_OPENINGSENSOR_GATE = 60
SUPLA_CHANNELFNC_OPENINGSENSOR_GARAGEDOOR = 70
SUPLA_CHANNELFNC_NOLIQUIDSENSOR = 80
SUPLA_CHANNELFNC_CONTROLLINGTHEDOORLOCK = 90
SUPLA_CHANNELFNC_OPENINGSENSOR_DOOR = 100
SUPLA_CHANNELFNC_CONTROLLINGTHEROLLERSHUTTER = 110
SUPLA_CHANNELFNC_CONTROLLINGTHEROOFWINDOW = 115
SUPLA_CHANNELFNC_OPENINGSENSOR_ROLLERSHUTTER = 120
SUPLA_CHANNELFNC_OPENINGSENSOR_ROOFWINDOW = 125
SUPLA_CHANNELFNC_POWERSWITCH = 130
SUPLA_CHANNELFNC_LIGHTSWITCH = 140
SUPLA_CHANNELFNC_RING = 150
SUPLA_CHANNELFNC_ALARM = 160
SUPLA_CHANNELFNC_NOTIFICATION = 170
SUPLA_CHANNELFNC_DIMMER = 180
SUPLA_CHANNELFNC_DIMMER_CCT = 185
SUPLA_CHANNELFNC_RGBLIGHTING = 190
SUPLA_CHANNELFNC_DIMMERANDRGBLIGHTING = 200
SUPLA_CHANNELFNC_DIMMER_CCT_AND_RGB = 205
SUPLA_CHANNELFNC_DEPTHSENSOR = 210
SUPLA_CHANNELFNC_DISTANCESENSOR = 220
SUPLA_CHANNELFNC_OPENINGSENSOR_WINDOW = 230
SUPLA_CHANNELFNC_HOTELCARDSENSOR = 235
SUPLA_CHANNELFNC_ALARMARMAMENTSENSOR = 236
SUPLA_CHANNELFNC_MAILSENSOR = 240
SUPLA_CHANNELFNC_WINDSENSOR = 250
SUPLA_CHANNELFNC_PRESSURESENSOR = 260
SUPLA_CHANNELFNC_RAINSENSOR = 270
SUPLA_CHANNELFNC_WEIGHTSENSOR = 280
SUPLA_CHANNELFNC_WEATHER_STATION = 290
SUPLA_CHANNELFNC_STAIRCASETIMER = 300
SUPLA_CHANNELFNC_ELECTRICITY_METER = 310
SUPLA_CHANNELFNC_IC_ELECTRICITY_METER = 315
SUPLA_CHANNELFNC_IC_GAS_METER = 320
SUPLA_CHANNELFNC_IC_WATER_METER = 330
SUPLA_CHANNELFNC_IC_HEAT_METER = 340
SUPLA_CHANNELFNC_IC_EVENTS = 350
SUPLA_CHANNELFNC_IC_SECONDS = 360
SUPLA_CHANNELFNC_THERMOSTAT_HEATPOL_HOMEPLUS = 410
SUPLA_CHANNELFNC_HVAC_THERMOSTAT = 420
SUPLA_CHANNELFNC_HVAC_THERMOSTAT_HEAT_COOL = 422
SUPLA_CHANNELFNC_HVAC_DRYER = 423
SUPLA_CHANNELFNC_HVAC_FAN = 424
SUPLA_CHANNELFNC_HVAC_THERMOSTAT_DIFFERENTIAL = 425
SUPLA_CHANNELFNC_HVAC_DOMESTIC_HOT_WATER = 426
SUPLA_CHANNELFNC_HVAC_HRV = 430
SUPLA_CHANNELFNC_VALVE_OPENCLOSE = 500
SUPLA_CHANNELFNC_VALVE_PERCENTAGE = 510
SUPLA_CHANNELFNC_GENERAL_PURPOSE_MEASUREMENT = 520
SUPLA_CHANNELFNC_GENERAL_PURPOSE_METER = 530
SUPLA_CHANNELFNC_CONTROLLINGTHEENGINESPEED = 600
SUPLA_CHANNELFNC_ACTIONTRIGGER = 700
SUPLA_CHANNELFNC_DIGIGLASS_HORIZONTAL = 800
SUPLA_CHANNELFNC_DIGIGLASS_VERTICAL = 810
SUPLA_CHANNELFNC_CONTROLLINGTHEFACADEBLIND = 900
SUPLA_CHANNELFNC_TERRACE_AWNING = 910
SUPLA_CHANNELFNC_PROJECTOR_SCREEN = 920
SUPLA_CHANNELFNC_CURTAIN = 930
SUPLA_CHANNELFNC_VERTICAL_BLIND = 940
SUPLA_CHANNELFNC_ROLLER_GARAGE_DOOR = 950
SUPLA_CHANNELFNC_PUMPSWITCH = 960
SUPLA_CHANNELFNC_HEATORCOLDSOURCESWITCH = 970
SUPLA_CHANNELFNC_CONTAINER = 980
SUPLA_CHANNELFNC_SEPTIC_TANK = 981
SUPLA_CHANNELFNC_WATER_TANK = 982
SUPLA_CHANNELFNC_CONTAINER_LEVEL_SENSOR = 990
SUPLA_CHANNELFNC_FLOOD_SENSOR = 1000
SUPLA_CHANNELFNC_MOTION_SENSOR = 1010
SUPLA_CHANNELFNC_BINARY_SENSOR = 1020

CHANNEL_FUNCTION_NAMES: dict[int, str] = {
    SUPLA_CHANNELFNC_NONE: "NONE",
    SUPLA_CHANNELFNC_CONTROLLINGTHEGATEWAYLOCK: "CONTROLLINGTHEGATEWAYLOCK",
    SUPLA_CHANNELFNC_CONTROLLINGTHEGATE: "CONTROLLINGTHEGATE",
    SUPLA_CHANNELFNC_CONTROLLINGTHEGARAGEDOOR: "CONTROLLINGTHEGARAGEDOOR",
    SUPLA_CHANNELFNC_THERMOMETER: "THERMOMETER",
    SUPLA_CHANNELFNC_HUMIDITY: "HUMIDITY",
    SUPLA_CHANNELFNC_HUMIDITYANDTEMPERATURE: "HUMIDITYANDTEMPERATURE",
    SUPLA_CHANNELFNC_OPENINGSENSOR_GATEWAY: "OPENINGSENSOR_GATEWAY",
    SUPLA_CHANNELFNC_OPENINGSENSOR_GATE: "OPENINGSENSOR_GATE",
    SUPLA_CHANNELFNC_OPENINGSENSOR_GARAGEDOOR: "OPENINGSENSOR_GARAGEDOOR",
    SUPLA_CHANNELFNC_NOLIQUIDSENSOR: "NOLIQUIDSENSOR",
    SUPLA_CHANNELFNC_CONTROLLINGTHEDOORLOCK: "CONTROLLINGTHEDOORLOCK",
    SUPLA_CHANNELFNC_OPENINGSENSOR_DOOR: "OPENINGSENSOR_DOOR",
    SUPLA_CHANNELFNC_CONTROLLINGTHEROLLERSHUTTER: "CONTROLLINGTHEROLLERSHUTTER",
    SUPLA_CHANNELFNC_CONTROLLINGTHEROOFWINDOW: "CONTROLLINGTHEROOFWINDOW",
    SUPLA_CHANNELFNC_OPENINGSENSOR_ROLLERSHUTTER: "OPENINGSENSOR_ROLLERSHUTTER",
    SUPLA_CHANNELFNC_OPENINGSENSOR_ROOFWINDOW: "OPENINGSENSOR_ROOFWINDOW",
    SUPLA_CHANNELFNC_POWERSWITCH: "POWERSWITCH",
    SUPLA_CHANNELFNC_LIGHTSWITCH: "LIGHTSWITCH",
    SUPLA_CHANNELFNC_RING: "RING",
    SUPLA_CHANNELFNC_ALARM: "ALARM",
    SUPLA_CHANNELFNC_NOTIFICATION: "NOTIFICATION",
    SUPLA_CHANNELFNC_DIMMER: "DIMMER",
    SUPLA_CHANNELFNC_DIMMER_CCT: "DIMMER_CCT",
    SUPLA_CHANNELFNC_RGBLIGHTING: "RGBLIGHTING",
    SUPLA_CHANNELFNC_DIMMERANDRGBLIGHTING: "DIMMERANDRGBLIGHTING",
    SUPLA_CHANNELFNC_DIMMER_CCT_AND_RGB: "DIMMER_CCT_AND_RGB",
    SUPLA_CHANNELFNC_DEPTHSENSOR: "DEPTHSENSOR",
    SUPLA_CHANNELFNC_DISTANCESENSOR: "DISTANCESENSOR",
    SUPLA_CHANNELFNC_OPENINGSENSOR_WINDOW: "OPENINGSENSOR_WINDOW",
    SUPLA_CHANNELFNC_HOTELCARDSENSOR: "HOTELCARDSENSOR",
    SUPLA_CHANNELFNC_ALARMARMAMENTSENSOR: "ALARMARMAMENTSENSOR",
    SUPLA_CHANNELFNC_MAILSENSOR: "MAILSENSOR",
    SUPLA_CHANNELFNC_WINDSENSOR: "WINDSENSOR",
    SUPLA_CHANNELFNC_PRESSURESENSOR: "PRESSURESENSOR",
    SUPLA_CHANNELFNC_RAINSENSOR: "RAINSENSOR",
    SUPLA_CHANNELFNC_WEIGHTSENSOR: "WEIGHTSENSOR",
    SUPLA_CHANNELFNC_WEATHER_STATION: "WEATHER_STATION",
    SUPLA_CHANNELFNC_STAIRCASETIMER: "STAIRCASETIMER",
    SUPLA_CHANNELFNC_ELECTRICITY_METER: "ELECTRICITY_METER",
    SUPLA_CHANNELFNC_IC_ELECTRICITY_METER: "IC_ELECTRICITY_METER",
    SUPLA_CHANNELFNC_IC_GAS_METER: "IC_GAS_METER",
    SUPLA_CHANNELFNC_IC_WATER_METER: "IC_WATER_METER",
    SUPLA_CHANNELFNC_IC_HEAT_METER: "IC_HEAT_METER",
    SUPLA_CHANNELFNC_IC_EVENTS: "IC_EVENTS",
    SUPLA_CHANNELFNC_IC_SECONDS: "IC_SECONDS",
    SUPLA_CHANNELFNC_THERMOSTAT_HEATPOL_HOMEPLUS: "THERMOSTAT_HEATPOL_HOMEPLUS",
    SUPLA_CHANNELFNC_HVAC_THERMOSTAT: "HVAC_THERMOSTAT",
    SUPLA_CHANNELFNC_HVAC_THERMOSTAT_HEAT_COOL: "HVAC_THERMOSTAT_HEAT_COOL",
    SUPLA_CHANNELFNC_HVAC_DRYER: "HVAC_DRYER",
    SUPLA_CHANNELFNC_HVAC_FAN: "HVAC_FAN",
    SUPLA_CHANNELFNC_HVAC_THERMOSTAT_DIFFERENTIAL: "HVAC_THERMOSTAT_DIFFERENTIAL",
    SUPLA_CHANNELFNC_HVAC_DOMESTIC_HOT_WATER: "HVAC_DOMESTIC_HOT_WATER",
    SUPLA_CHANNELFNC_HVAC_HRV: "HVAC_HRV",
    SUPLA_CHANNELFNC_VALVE_OPENCLOSE: "VALVE_OPENCLOSE",
    SUPLA_CHANNELFNC_VALVE_PERCENTAGE: "VALVE_PERCENTAGE",
    SUPLA_CHANNELFNC_GENERAL_PURPOSE_MEASUREMENT: "GENERAL_PURPOSE_MEASUREMENT",
    SUPLA_CHANNELFNC_GENERAL_PURPOSE_METER: "GENERAL_PURPOSE_METER",
    SUPLA_CHANNELFNC_CONTROLLINGTHEENGINESPEED: "CONTROLLINGTHEENGINESPEED",
    SUPLA_CHANNELFNC_ACTIONTRIGGER: "ACTIONTRIGGER",
    SUPLA_CHANNELFNC_DIGIGLASS_HORIZONTAL: "DIGIGLASS_HORIZONTAL",
    SUPLA_CHANNELFNC_DIGIGLASS_VERTICAL: "DIGIGLASS_VERTICAL",
    SUPLA_CHANNELFNC_CONTROLLINGTHEFACADEBLIND: "CONTROLLINGTHEFACADEBLIND",
    SUPLA_CHANNELFNC_TERRACE_AWNING: "TERRACE_AWNING",
    SUPLA_CHANNELFNC_PROJECTOR_SCREEN: "PROJECTOR_SCREEN",
    SUPLA_CHANNELFNC_CURTAIN: "CURTAIN",
    SUPLA_CHANNELFNC_VERTICAL_BLIND: "VERTICAL_BLIND",
    SUPLA_CHANNELFNC_ROLLER_GARAGE_DOOR: "ROLLER_GARAGE_DOOR",
    SUPLA_CHANNELFNC_PUMPSWITCH: "PUMPSWITCH",
    SUPLA_CHANNELFNC_HEATORCOLDSOURCESWITCH: "HEATORCOLDSOURCESWITCH",
    SUPLA_CHANNELFNC_CONTAINER: "CONTAINER",
    SUPLA_CHANNELFNC_SEPTIC_TANK: "SEPTIC_TANK",
    SUPLA_CHANNELFNC_WATER_TANK: "WATER_TANK",
    SUPLA_CHANNELFNC_CONTAINER_LEVEL_SENSOR: "CONTAINER_LEVEL_SENSOR",
    SUPLA_CHANNELFNC_FLOOD_SENSOR: "FLOOD_SENSOR",
    SUPLA_CHANNELFNC_MOTION_SENSOR: "MOTION_SENSOR",
    SUPLA_CHANNELFNC_BINARY_SENSOR: "BINARY_SENSOR",
}

# RGBW commands (TRGBW_Value.command)
RGBW_COMMAND_NOT_SET = 0
RGBW_COMMAND_TURN_ON_DIMMER = 1
RGBW_COMMAND_TURN_OFF_DIMMER = 2
RGBW_COMMAND_TOGGLE_DIMMER = 3
RGBW_COMMAND_TURN_ON_RGB = 4
RGBW_COMMAND_TURN_OFF_RGB = 5
RGBW_COMMAND_TOGGLE_RGB = 6
RGBW_COMMAND_TURN_ON_ALL = 7
RGBW_COMMAND_TURN_OFF_ALL = 8
RGBW_COMMAND_TOGGLE_ALL = 9

# Roller shutter command values (server -> device)
RS_CMD_STOP = 0
RS_CMD_DOWN = 1
RS_CMD_UP = 2
RS_CMD_DOWN_OR_STOP = 3
RS_CMD_UP_OR_STOP = 4
RS_CMD_STEP_BY_STEP = 5
RS_POSITION_OFFSET = 10

# HVAC modes
SUPLA_HVAC_MODE_NOT_SET = 0
SUPLA_HVAC_MODE_OFF = 1
SUPLA_HVAC_MODE_HEAT = 2
SUPLA_HVAC_MODE_COOL = 3
SUPLA_HVAC_MODE_HEAT_COOL = 4
SUPLA_HVAC_MODE_FAN_ONLY = 6
SUPLA_HVAC_MODE_DRY = 7
SUPLA_HVAC_MODE_CMD_TURN_ON = 8
SUPLA_HVAC_MODE_CMD_WEEKLY_SCHEDULE = 9
SUPLA_HVAC_MODE_CMD_SWITCH_TO_MANUAL = 10

HVAC_MODE_NAMES: dict[int, str] = {
    SUPLA_HVAC_MODE_NOT_SET: "NOT_SET",
    SUPLA_HVAC_MODE_OFF: "OFF",
    SUPLA_HVAC_MODE_HEAT: "HEAT",
    SUPLA_HVAC_MODE_COOL: "COOL",
    SUPLA_HVAC_MODE_HEAT_COOL: "HEAT_COOL",
    SUPLA_HVAC_MODE_FAN_ONLY: "FAN_ONLY",
    SUPLA_HVAC_MODE_DRY: "DRY",
    SUPLA_HVAC_MODE_CMD_TURN_ON: "CMD_TURN_ON",
    SUPLA_HVAC_MODE_CMD_WEEKLY_SCHEDULE: "CMD_WEEKLY_SCHEDULE",
    SUPLA_HVAC_MODE_CMD_SWITCH_TO_MANUAL: "CMD_SWITCH_TO_MANUAL",
}

SUPLA_HVAC_VALUE_FLAG_SETPOINT_TEMP_HEAT_SET = 1 << 0
SUPLA_HVAC_VALUE_FLAG_SETPOINT_TEMP_COOL_SET = 1 << 1
SUPLA_HVAC_VALUE_FLAG_HEATING = 1 << 2
SUPLA_HVAC_VALUE_FLAG_COOLING = 1 << 3
SUPLA_HVAC_VALUE_FLAG_WEEKLY_SCHEDULE = 1 << 4

# TDSC_ChannelState.Fields - which members the device actually filled in.
SUPLA_CHANNELSTATE_FIELD_IPV4 = 0x0001
SUPLA_CHANNELSTATE_FIELD_MAC = 0x0002
SUPLA_CHANNELSTATE_FIELD_BATTERYLEVEL = 0x0004
SUPLA_CHANNELSTATE_FIELD_BATTERYPOWERED = 0x0008
SUPLA_CHANNELSTATE_FIELD_WIFIRSSI = 0x0010
SUPLA_CHANNELSTATE_FIELD_WIFISIGNALSTRENGTH = 0x0020
SUPLA_CHANNELSTATE_FIELD_BRIDGENODESIGNALSTRENGTH = 0x0040
SUPLA_CHANNELSTATE_FIELD_UPTIME = 0x0080
SUPLA_CHANNELSTATE_FIELD_CONNECTIONUPTIME = 0x0100
SUPLA_CHANNELSTATE_FIELD_BATTERYHEALTH = 0x0200
SUPLA_CHANNELSTATE_FIELD_BRIDGENODEONLINE = 0x0400
SUPLA_CHANNELSTATE_FIELD_LASTCONNECTIONRESETCAUSE = 0x0800
SUPLA_CHANNELSTATE_FIELD_LIGHTSOURCELIFESPAN = 0x1000
SUPLA_CHANNELSTATE_FIELD_LIGHTSOURCEOPERATINGTIME = 0x2000
SUPLA_CHANNELSTATE_FIELD_OPERATINGTIME = 0x4000
SUPLA_CHANNELSTATE_FIELD_SWITCHCYCLECOUNT = 0x8000
SUPLA_CHANNELSTATE_FIELD_DEVICE_BATTERYLEVEL = 0x10000

SUPLA_LASTCONNECTIONRESETCAUSE_UNKNOWN = 0
SUPLA_LASTCONNECTIONRESETCAUSE_ACTIVITY_TIMEOUT = 1
SUPLA_LASTCONNECTIONRESETCAUSE_WIFI_CONNECTION_LOST = 2
SUPLA_LASTCONNECTIONRESETCAUSE_SERVER_CONNECTION_LOST = 3

CONNECTION_RESET_CAUSE_NAMES: dict[int, str] = {
    SUPLA_LASTCONNECTIONRESETCAUSE_UNKNOWN: "unknown",
    SUPLA_LASTCONNECTIONRESETCAUSE_ACTIVITY_TIMEOUT: "activity_timeout",
    SUPLA_LASTCONNECTIONRESETCAUSE_WIFI_CONNECTION_LOST: "wifi_connection_lost",
    SUPLA_LASTCONNECTIONRESETCAUSE_SERVER_CONNECTION_LOST: "server_connection_lost",
}

# Extended value types
EV_TYPE_ELECTRICITY_METER_MEASUREMENT_V3 = 14
EV_TYPE_IMPULSE_COUNTER_DETAILS_V1 = 20
EV_TYPE_THERMOSTAT_DETAILS_V1 = 30
EV_TYPE_CHANNEL_STATE_V1 = 40
EV_TYPE_TIMER_STATE_V1 = 50
EV_TYPE_TIMER_STATE_V1_SEC = 51
EV_TYPE_CHANNEL_AND_TIMER_STATE_V1 = 60
EV_TYPE_MULTI_VALUE = 100

REGISTER_DEVICE_CALLS = frozenset(
    {
        SUPLA_DS_CALL_REGISTER_DEVICE,
        SUPLA_DS_CALL_REGISTER_DEVICE_B,
        SUPLA_DS_CALL_REGISTER_DEVICE_C,
        SUPLA_DS_CALL_REGISTER_DEVICE_D,
        SUPLA_DS_CALL_REGISTER_DEVICE_E,
        SUPLA_DS_CALL_REGISTER_DEVICE_F,
        SUPLA_DS_CALL_REGISTER_DEVICE_G,
    }
)

CHANNEL_VALUE_CHANGED_CALLS = frozenset(
    {
        SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED,
        SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED_B,
        SUPLA_DS_CALL_DEVICE_CHANNEL_VALUE_CHANGED_C,
    }
)
